server:
  port: 8081

spring:
  application:
    name: worker-service

  datasource:
    url: jdbc:postgresql://localhost:5432/jobsdb
    username: jobuser
    password: jobpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: job-worker-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics